import { useEffect, useState } from 'react'
import { Newspaper, RefreshCw, MapPin, ExternalLink, Globe2 } from 'lucide-react'

export default function NewsHub() {
  const [place,setPlace]=useState('Coimbatore, Tamil Nadu'), [draft,setDraft]=useState('Coimbatore, Tamil Nadu'), [tab,setTab]=useState('all'), [items,setItems]=useState([]), [loading,setLoading]=useState(true), [error,setError]=useState('')
  async function load(p=place){ setLoading(true); setError(''); try { const res=await fetch(`/api/news?place=${encodeURIComponent(p)}`,{cache:'no-store'}); const data=await res.json().catch(()=>({})); if(!res.ok) throw new Error(data.error||`News endpoint returned ${res.status}`); setItems(data.items||[]) } catch(e){setError(e.message||'News unavailable')} finally{setLoading(false)} }
  useEffect(()=>{load()},[])
  useEffect(()=>{ const onOnline=()=>load(); window.addEventListener('online',onOnline); return ()=>window.removeEventListener('online',onOnline) },[place])
  const visible=items.filter(x=>tab==='all'||x.type===tab)
  return <div className="space-y-4">
    <div className="rm-card p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><div className="rm-kicker">News</div><h2 className="font-display text-2xl font-extrabold mt-1">Daily news</h2><p className="text-sm text-ink-soft mt-1">A simple feed of headlines. Open the original source to read the full story.</p></div><Newspaper className="text-brand"/></div>
      <div className="flex flex-col sm:flex-row gap-2 mt-4"><label className="flex-1 relative"><MapPin className="absolute left-3 top-3.5 text-ink-soft" size={16}/><input className="pl-9" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Place for local news"/></label><button onClick={()=>{setPlace(draft);load(draft)}} className="rounded-xl bg-brand text-white px-4 py-2.5 text-sm font-bold">Set place</button><button onClick={()=>load()} className="rounded-xl border px-4 py-2.5 text-sm font-semibold inline-flex items-center justify-center gap-2"><RefreshCw size={15}/> Refresh</button></div>
      <div className="flex gap-2 mt-3 overflow-x-auto"><button onClick={()=>setTab('all')} className={`rounded-full px-3 py-1.5 text-xs font-bold ${tab==='all'?'bg-brand text-white':'bg-paper border'}`}>All</button><button onClick={()=>setTab('local')} className={`rounded-full px-3 py-1.5 text-xs font-bold ${tab==='local'?'bg-brand text-white':'bg-paper border'}`}>Local</button><button onClick={()=>setTab('common')} className={`rounded-full px-3 py-1.5 text-xs font-bold ${tab==='common'?'bg-brand text-white':'bg-paper border'}`}>India / Common</button></div>
    </div>
    {error&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">{error}</div>}
    {loading?<div className="rm-card p-8 text-center text-sm text-ink-soft">Loading headlines…</div>:visible.length?<div className="grid grid-cols-1 lg:grid-cols-2 gap-3">{visible.map(x=><article key={x.id} className="rm-card p-4"><div className="flex items-center gap-2 text-xs text-ink-soft"><span className="rounded-full bg-brand/10 text-brand px-2 py-1 font-bold">{x.type==='local'?'Local':'Common'}</span><span>{x.source}</span></div><h3 className="font-display text-lg font-bold text-ink mt-2">{x.title}</h3>{x.summary&&<p className="text-sm text-ink-soft mt-2 leading-6">{x.summary}</p>}<a href={x.url} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-2 text-sm font-bold text-brand">Read original <ExternalLink size={14}/></a></article>)}</div>:<div className="rm-card p-8 text-center"><Globe2 className="mx-auto text-ink-soft mb-2"/><p className="font-semibold text-ink">No headlines available for this place.</p><p className="text-sm text-ink-soft mt-1">Add approved RSS feed URLs to NEWS_FEED_URLS for local sources.</p></div>}
    <p className="text-[11px] text-ink-soft">News is shown as short headline/summary metadata with a link to the original publisher. Feed terms and copyright permissions must be respected before adding commercial publisher feeds.</p>
  </div>
}
