import { useEffect, useState } from 'react'
import { Wifi, Plus, Heart, Phone, IndianRupee, ShieldCheck, Check, X } from 'lucide-react'
import { useAuth } from '../../context/AuthContext'
import { listHouses } from '../../services/houseService'
import { createWifiInterest, createWifiShare, deleteWifiShare, listMyWifiShares, listWifiInterests, listWifiShares, updateWifiInterest, updateWifiShare } from '../../services/wifiShareService'

export default function WifiShareBoard({ ownerOnly=false }) {
  const { user } = useAuth()
  const owner = user?.role === 'owner' || user?.role === 'admin'
  const canOffer = owner || user?.role === 'tenant'
  const [listings,setListings] = useState([]), [mine,setMine] = useState([]), [interests,setInterests] = useState([]), [houses,setHouses] = useState([])
  const [show,setShow] = useState(false), [form,setForm] = useState({houseId:'', speedMbps:'', monthlyShare:'', maxMembers:1, providerPhone:'', notes:'', contactAllowed:false})
  const [message,setMessage] = useState('')
  useEffect(()=>{ Promise.all([listWifiShares(), canOffer?listMyWifiShares(user.uid):Promise.resolve([]), canOffer?listWifiInterests(user.uid):Promise.resolve([]), owner?listHouses():Promise.resolve([])]).then(([a,b,c,d])=>{setListings(a);setMine(b);setInterests(c);setHouses(d); if(d[0]) setForm(v=>({...v,houseId:d[0].id})) }).catch(e=>setMessage(e.message)) },[user?.uid,owner,canOffer])
  async function reload(){ setListings(await listWifiShares()); if(canOffer){setMine(await listMyWifiShares(user.uid));setInterests(await listWifiInterests(user.uid))} }
  async function submit(e){ e.preventDefault(); const h = owner ? houses.find(x=>x.id===form.houseId) : { id:user?.houseId, internalDoorNumber:user?.houseLabel || 'My house' }; if(!h?.id || !form.monthlyShare) return; try { await createWifiShare({ ownerUid:user.uid, houseId:h.id, houseLabel:h.internalDoorNumber||h.id, speedMbps:Number(form.speedMbps||0), monthlyShare:Number(form.monthlyShare), maxMembers:Number(form.maxMembers||1), providerPhone:form.contactAllowed?String(form.providerPhone||'').trim():null, notes:String(form.notes||'').trim() }); await reload(); setShow(false); setMessage('Wi-Fi sharing offer published.') } catch(e){setMessage(e.message)} }
  async function interest(l){ try { await createWifiInterest({listingId:l.id, ownerUid:l.ownerUid, seekerUid:user.uid, seekerName:user.name||'Resident', message:'I am interested in sharing this connection.', houseId:l.houseId}); setMessage('Interest sent to the Wi-Fi provider.') } catch(e){setMessage(e.message)} }
  if(ownerOnly && !owner) return null
  return <div className="space-y-4">
    <div className="rm-card p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><div className="rm-kicker">Community Wi-Fi</div><h2 className="font-display text-xl font-extrabold mt-1">Share Wi-Fi with neighbours</h2><p className="text-sm text-ink-soft mt-1">Offer spare internet capacity or find a neighbour willing to share monthly costs.</p></div><Wifi className="text-brand"/></div>
      {canOffer && <button onClick={()=>setShow(v=>!v)} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-brand px-4 py-2.5 text-sm font-bold text-white"><Plus size={16}/> Offer my Wi-Fi</button>}
      {message && <div className="mt-3 rounded-xl border border-brand/15 bg-brand/5 p-3 text-sm text-ink">{message}</div>}
    </div>
    {show && canOffer && <form onSubmit={submit} className="rm-card p-4 sm:p-5 grid sm:grid-cols-2 gap-3">{owner ? <label className="text-xs font-semibold text-ink-soft">House<select value={form.houseId} onChange={e=>setForm(v=>({...v,houseId:e.target.value}))}>{houses.map(h=><option key={h.id} value={h.id}>{h.internalDoorNumber} · {h.tenantName||'Vacant'}</option>)}</select></label> : <div className="rounded-xl bg-paper p-3 text-sm font-semibold text-ink">Your house: {user?.houseLabel || 'Current house'}</div>}<label className="text-xs font-semibold text-ink-soft">Speed (Mbps)<input type="number" min="1" value={form.speedMbps} onChange={e=>setForm(v=>({...v,speedMbps:e.target.value}))}/></label><label className="text-xs font-semibold text-ink-soft">Monthly share ₹<input type="number" min="0" value={form.monthlyShare} onChange={e=>setForm(v=>({...v,monthlyShare:e.target.value}))}/></label><label className="text-xs font-semibold text-ink-soft">Maximum people<input type="number" min="1" max="20" value={form.maxMembers} onChange={e=>setForm(v=>({...v,maxMembers:e.target.value}))}/></label><label className="sm:col-span-2 text-xs font-semibold text-ink-soft">Notes<textarea value={form.notes} onChange={e=>setForm(v=>({...v,notes:e.target.value}))} placeholder="Example: evenings are usually available."/></label><label className="sm:col-span-2 flex items-center gap-2 text-sm text-ink"><input type="checkbox" checked={form.contactAllowed} onChange={e=>setForm(v=>({...v,contactAllowed:e.target.checked}))}/> Allow interested residents to see my contact number</label>{form.contactAllowed&&<label className="text-xs font-semibold text-ink-soft">Contact number<input value={form.providerPhone} onChange={e=>setForm(v=>({...v,providerPhone:e.target.value}))}/></label>}<div className="sm:col-span-2 flex gap-2"><button className="rounded-xl bg-brand text-white px-4 py-2.5 text-sm font-bold">Publish</button><button type="button" onClick={()=>setShow(false)} className="rounded-xl border px-4 py-2.5 text-sm font-semibold">Cancel</button></div></form>}
    {!ownerOnly && <div className="space-y-3">{listings.map(l=><div key={l.id} className="rm-card p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-ink">{l.houseLabel} · Wi-Fi sharing</p><p className="text-sm text-ink-soft mt-1">{l.speedMbps ? `${l.speedMbps} Mbps · `:''}up to {l.maxMembers} people</p></div><span className="rounded-full bg-brand/10 text-brand px-2.5 py-1 text-xs font-bold">₹{l.monthlyShare}/month</span></div><p className="text-sm text-ink-soft mt-3">{l.notes || 'Neighbour is open to sharing the connection.'}</p><div className="flex flex-wrap gap-2 mt-3"><button onClick={()=>interest(l)} className="inline-flex items-center gap-2 rounded-xl bg-brand px-3 py-2 text-sm font-bold text-white"><Heart size={15}/> I’m interested</button>{l.providerPhone && <a href={`tel:${l.providerPhone}`} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-semibold"><Phone size={15}/> Contact</a>}</div></div>)}{listings.length===0&&<div className="rm-card p-8 text-center text-sm text-ink-soft">No active Wi-Fi sharing offers yet.</div>}</div>}
    {canOffer && <div className="space-y-3"><h3 className="font-display text-lg font-bold text-ink">My Wi-Fi offers</h3>{mine.map(l=><div key={l.id} className="rm-card p-4 flex items-center justify-between gap-3"><div><p className="font-semibold text-ink">{l.houseLabel} · ₹{l.monthlyShare}/month</p><p className="text-xs text-ink-soft">{l.speedMbps||'—'} Mbps · {l.status}</p></div><div className="flex gap-2"><button onClick={()=>updateWifiShare(l.id,{status:l.status==='active'?'paused':'active'}).then(reload)} className="rounded-lg border px-3 py-2 text-xs font-bold">{l.status==='active'?'Pause':'Resume'}</button><button onClick={()=>deleteWifiShare(l.id).then(reload)} className="rounded-lg border px-3 py-2 text-xs font-bold text-red-600">Delete</button></div></div>)}{interests.length>0&&<div className="rm-card p-4"><p className="font-bold text-ink">Interested residents</p><div className="mt-2 space-y-2">{interests.map(i=><div key={i.id} className="flex items-center justify-between gap-2 rounded-xl bg-paper p-3"><div><p className="font-semibold text-ink">{i.seekerName}</p><p className="text-xs text-ink-soft">{i.status}</p></div><div className="flex gap-1"><button onClick={()=>updateWifiInterest(i.id,'accepted').then(reload)} className="p-2 text-brand" title="Accept"><Check size={16}/></button><button onClick={()=>updateWifiInterest(i.id,'declined').then(reload)} className="p-2 text-red-600" title="Decline"><X size={16}/></button></div></div>)}</div></div>}</div>}
    <div className="text-xs text-ink-soft flex items-start gap-2"><ShieldCheck size={14} className="mt-0.5 shrink-0"/> Never publish your Wi-Fi password in this listing. Share access directly and follow your ISP's terms. Paid/public resale may require separate authorization.</div>
  </div>
}
