import { motion } from 'framer-motion'
import { ArrowRight, ShieldCheck, ReceiptIndianRupee, Home, Bell, FileLock2, Smartphone, Languages, CheckCircle2, Menu, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'

const FEATURES = [
  { icon: ReceiptIndianRupee, title: 'Rent & bills in one place', text: 'Track rent, EB, water, advances, approvals and receipts without spreadsheets.' },
  { icon: Home, title: 'Know every home', text: 'See occupancy, tenant details, documents, maintenance and payment history together.' },
  { icon: Bell, title: 'Stay ahead of tasks', text: 'Notices, reminders, complaints and service requests stay visible and organised.' },
  { icon: ShieldCheck, title: 'Privacy-first by design', text: 'Private resident records and documents are protected with role-based access.' },
]
const ROLES = [
  ['Owners', 'Run the property, approve payments, manage houses and keep the ledger accurate.'],
  ['Co-owners', 'Work from the same operational view without sharing passwords.'],
  ['Tenants', 'Pay rent and bills, upload documents, raise requests and read notices.'],
]

export default function PublicHome() {
  const [menuOpen, setMenuOpen] = useState(false)
  const navigate = useNavigate()
  useEffect(() => { localStorage.setItem('rm_public_visited', '1') }, [])
  function start() { localStorage.setItem('rm_public_visited', '1'); navigate('/login') }
  return (
    <div className="rm-public min-h-[100dvh] overflow-x-hidden bg-paper text-ink">
      <header className="sticky top-0 z-50 border-b border-[var(--rm-border)]/80 bg-paper/85 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8">
          <Link to="/" className="flex items-center gap-3" aria-label="Rental Manager home"><span className="rm-logo-mark">R</span><span><span className="block font-display text-base font-extrabold leading-none">Rental Manager</span><span className="mt-1 block text-[10px] font-semibold uppercase tracking-[.16em] text-ink-soft">Property workspace</span></span></Link>
          <nav className="hidden items-center gap-7 text-sm font-semibold md:flex" aria-label="Main navigation"><a href="#features" className="text-ink-soft transition hover:text-ink">Features</a><a href="#roles" className="text-ink-soft transition hover:text-ink">For residents</a><Link to="/privacy" className="text-ink-soft transition hover:text-ink">Privacy</Link><button onClick={start} className="rm-public-nav-cta">Sign in <ArrowRight size={15} /></button></nav>
          <button className="md:hidden rm-icon-button" onClick={() => setMenuOpen(v => !v)} aria-label={menuOpen ? 'Close menu' : 'Open menu'}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button>
        </div>
        {menuOpen && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} className="border-t border-[var(--rm-border)] bg-paper-raised px-5 py-4 md:hidden"><div className="grid gap-1 text-sm font-semibold"><a href="#features" onClick={() => setMenuOpen(false)} className="rounded-xl px-3 py-3">Features</a><a href="#roles" onClick={() => setMenuOpen(false)} className="rounded-xl px-3 py-3">For residents</a><Link to="/privacy" onClick={() => setMenuOpen(false)} className="rounded-xl px-3 py-3">Privacy</Link><button onClick={start} className="mt-2 rounded-xl bg-cover px-4 py-3 text-left font-bold text-white">Sign in <ArrowRight size={15} className="inline" /></button></div></motion.div>}
      </header>
      <main>
        <section className="relative isolate"><div className="rm-orb rm-orb-one" /><div className="rm-orb rm-orb-two" /><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-14 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:pb-28 lg:pt-20">
          <motion.div initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .65 }}><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-brand/20 bg-brand/8 px-3 py-1.5 text-xs font-bold text-brand"><span className="h-2 w-2 animate-pulse rounded-full bg-brand" /> A calmer way to manage your property</div><h1 className="max-w-3xl font-display text-5xl font-extrabold leading-[.98] tracking-[-.045em] sm:text-6xl lg:text-7xl">Your property.<br /><span className="text-brand">One clear ledger.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-ink-soft sm:text-xl">Rental Manager brings houses, tenants, rent, utility bills, documents and day-to-day communication into one private workspace for owners and residents.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={start} className="rm-hero-button">Open Rental Manager <ArrowRight size={18} /></button><Link to="/terms" className="rm-secondary-button">Read how it works</Link></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-ink-soft"><span className="inline-flex items-center gap-1.5"><CheckCircle2 size={14} className="text-brand" /> Owner & tenant access</span><span className="inline-flex items-center gap-1.5"><CheckCircle2 size={14} className="text-brand" /> Rent & utility ledger</span><span className="inline-flex items-center gap-1.5"><CheckCircle2 size={14} className="text-brand" /> Mobile ready</span></div></motion.div>
          <motion.div initial={{ opacity: 0, scale: .96, y: 18 }} animate={{ opacity: 1, scale: 1, y: 0 }} transition={{ duration: .7, delay: .1 }} className="relative"><div className="rm-dashboard-preview"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div><p className="text-[10px] uppercase tracking-[.18em] text-white/45">Property overview</p><p className="mt-1 font-display text-lg font-extrabold text-white">Good morning</p></div><span className="rm-preview-avatar">R</span></div><div className="grid grid-cols-2 gap-3 p-4"><PreviewCard icon={ReceiptIndianRupee} value="₹60,000" label="Collected this month" /><PreviewCard icon={Home} value="50%" label="Occupancy" /><PreviewCard icon={CheckCircle2} value="0" label="Rent approvals" /><PreviewCard icon={Bell} value="0" label="Open complaints" /></div><div className="mx-4 mb-4 rounded-2xl bg-white/8 p-4"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-[.14em] text-white/45">Action centre</span><span className="rounded-full bg-emerald-400/15 px-2 py-1 text-xs font-bold text-emerald-300">Clear</span></div><div className="mt-4 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-400/10 text-emerald-300"><CheckCircle2 size={20} /></div><div><p className="font-bold text-white">Everything is under control</p><p className="text-xs text-white/45">Your next task is never hidden.</p></div></div></div></div><motion.div className="rm-float-card" animate={{ y: [0, -8, 0] }} transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}><ShieldCheck size={17} /><span>Private resident records</span></motion.div></motion.div>
        </div></section>
        <section id="features" className="border-y border-[var(--rm-border)] bg-paper-raised/70"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-20"><div className="max-w-2xl"><p className="rm-kicker text-brand">Everything in one place</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-[-.03em] sm:text-4xl">Built around the work you actually do.</h2><p className="mt-4 text-ink-soft leading-7">The interface is designed to keep everyday property work quick while keeping sensitive resident information behind the right access.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{FEATURES.map((f, i) => <motion.article key={f.title} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-50px' }} transition={{ delay: i * .06 }} className="rm-public-card"><div className="rm-feature-icon"><f.icon size={20} /></div><h3 className="mt-5 font-display text-lg font-extrabold">{f.title}</h3><p className="mt-2 text-sm leading-6 text-ink-soft">{f.text}</p></motion.article>)}</div></div></section>
        <section id="roles" className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-20"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="rm-kicker text-brand">One workspace, different views</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-[-.03em] sm:text-4xl">Simple for residents. Powerful for owners.</h2><p className="mt-4 leading-7 text-ink-soft">Everyone sees the tools relevant to their role, while the property ledger stays consistent behind the scenes.</p></div><div className="grid gap-3 sm:grid-cols-3">{ROLES.map(([title, text], i) => <motion.div key={title} whileHover={{ y: -4 }} transition={{ duration: .18 }} className="rm-role-card"><span className="rm-role-number">0{i + 1}</span><h3 className="mt-8 font-display text-xl font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-ink-soft">{text}</p></motion.div>)}</div></div></section>
        <section className="mx-auto max-w-7xl px-5 pb-16 lg:px-8 lg:pb-20"><div className="rm-trust-panel"><div><p className="rm-kicker text-emerald-300">Privacy & trust</p><h2 className="mt-2 font-display text-3xl font-extrabold text-white">Resident data deserves a careful home.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/60">Rental Manager separates owner and tenant access and treats identity documents, contact details and payment records as private operational data.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Trust icon={FileLock2} label="Private documents" /><Trust icon={ShieldCheck} label="Role-based access" /><Trust icon={Smartphone} label="Mobile ready" /><Trust icon={Languages} label="English + Tamil" /></div></div></section>
      </main>
      <footer className="border-t border-[var(--rm-border)] bg-paper-raised"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-8 text-sm lg:flex-row lg:items-center lg:justify-between lg:px-8"><div><p className="font-display font-extrabold">Rental Manager</p><p className="mt-1 text-xs text-ink-soft">Private property-management workspace.</p></div><nav className="flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-ink-soft"><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/acceptable-use">Acceptable use</Link><Link to="/data-policy">Data & documents</Link></nav></div></footer>
    </div>
  )
}
function PreviewCard({ icon: Icon, value, label }) { return <div className="rounded-2xl border border-white/8 bg-white/6 p-4"><Icon size={16} className="text-emerald-300" /><p className="mt-5 font-mono-tab text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-[11px] text-white/45">{label}</p></div> }
function Trust({ icon: Icon, label }) { return <div className="rounded-2xl border border-white/10 bg-white/5 p-4"><Icon size={18} className="text-emerald-300" /><p className="mt-4 text-xs font-bold text-white/75">{label}</p></div> }
